module.exports = {
  'rules': {
    'array-bracket-spacing': [2, 'never'],
    'block-spacing': [2, 'always'],
    'brace-style': [2, '1tbs', { allowSingleLine: true }],
    'camelcase': [2, { properties: 'always' }],
    'comma-spacing': [2, { before: false, after: true }],
    'comma-style': [2, 'last'],
    'computed-property-spacing': [2, 'never'],
    'consistent-this': [2, '_this'],
    'eol-last': 2,
    'func-names': 1,
    'func-style': 0,
    'id-length': 0,
    'id-match': 0,
    'indent': [2, 2, { SwitchCase: 0 }],
    'jsx-quotes': [2, 'prefer-double'],
    'key-spacing': [2, { beforeColon: false, afterColon: true }],
    'linebreak-style': [2, 'unix'],
    'lines-around-comment': 0,
    'max-nested-callbacks': [2, 3],
    'new-cap': 2,
    'new-parens': 2,
    'newline-after-var': 0,
    'no-array-constructor': 2,
    'no-continue': 2,
    'no-inline-comments': 0,
    'no-lonely-if': 2,
    'no-mixed-spaces-and-tabs': 2,
    'no-multiple-empty-lines': [2, { max: 3, maxEOF: 1 }],
    'no-negated-condition': 1,
    'no-nested-ternary': 2,
    'no-new-object': 2,
    'no-restricted-syntax': [2, 'WithStatement'],
    'no-spaced-func': 2,
    'no-ternary': 0,
    'no-trailing-spaces': 2,
    'no-underscore-dangle': 0,
    'no-unneeded-ternary': 2,
    'object-curly-spacing': [2, 'always'],
    'one-var': [2, 'never'],
    'operator-assignment': [1, 'always'],
    'operator-linebreak': [2, 'after'],
    'padded-blocks': [2, 'never'],
    'quote-props': [2, 'as-needed', { keywords: true }],
    'quotes': [2, 'single', 'avoid-escape'],
    'require-jsdoc': 0,
    'semi-spacing': [2, { before: false, after: true }],
    'semi': [2, 'always'],
    'sort-vars': 0,
    'keyword-spacing': 2,
    'space-before-function-paren': [2, 'never'],
    'space-in-parens': [2, 'never'],
    'space-infix-ops': 2,
    'space-unary-ops': [2, { words: true, nonwords: false }],
    'spaced-comment': [2, 'always', { block: { exceptions: ['*', '!'] } }],
    'wrap-regex': 0,
    'max-depth': [1, 4],
    'max-len': [2, 120, 2, {
      'ignoreUrls': true,
      'ignoreComments': false
    }],
    'max-params': [2, 4],
    'max-statements': [0, 10],
    'no-bitwise': 0,
    'no-plusplus': 0
  }
};
